port = 8080
name = much_wow
errorPage404 = /error404.html
errorPage403 = /error505.html
clientMaxBodySize = 500

#routes:
<CGI>
	methods = GET, POST
	directoryListening = on
	root = /tmp/CGI
	uploadDir = /tmp/uploads
	index = upload.html
</CGI>

<static>
	methods = GET, POST, DELETE
	directoryListening = off
	index = index.html
</static>
